
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 05 18:03:32 CEST 2013
//----------------------------------------------------

package analyseur;

/** CUP generated interface containing symbol constants. */
public interface AnalyseurSyntaxiqueSym {
  /* terminals */
  public static final int LI = 2;
  public static final int error = 1;
  public static final int SAUT = 5;
  public static final int SOUS = 4;
  public static final int CHAINE = 6;
  public static final int EOF = 0;
  public static final int TITRE = 3;
}

